### ISSUE TITLE
`HttpExchange.pathParams` are not initalized for before() handlers in case of 404 requests

### ISSUE THREAD

**Issue by cbxp** [codeborne/klite#82]
We are getting these error in production:

```kotlin
kotlin.UninitializedPropertyAccessException: lateinit property pathParams has not been initialized
	at klite.HttpExchange.getPathParams(HttpExchange.kt:36)
	at klite.HttpExchange.path(HttpExchange.kt:37)
	at auth.PathParamChecks.before(PathParamChecks.kt:30)
        ...
	at klite.jdbc.RequestTransactionHandler$decorate$2.invokeSuspend(RequestTransactionHandler.kt:29)
	at klite.jdbc.RequestTransactionHandler$decorate$2.invoke(RequestTransactionHandler.kt)
	at klite.jdbc.RequestTransactionHandler$decorate$2.invoke(RequestTransactionHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at klite.jdbc.RequestTransactionHandler.decorate(RequestTransactionHandler.kt:27)
	at klite.jdbc.RequestTransactionHandler$install$1$1.invokeSuspend(RequestTransactionHandler.kt:20)
	at klite.jdbc.RequestTransactionHandler$install$1$1.invoke(RequestTransactionHandler.kt)
	at klite.jdbc.RequestTransactionHandler$install$1$1.invoke(RequestTransactionHandler.kt)
        ...
	at klite.Server.runHandler(Server.kt:98)
	at klite.Server.access$runHandler(Server.kt:20)
	at klite.Server$context$2$1.invokeSuspend(Server.kt:76)
	at klite.Server$context$2$1.invoke(Server.kt)
	at klite.Server$context$2$1.invoke(Server.kt)
	at klite.Server$addContext$1$1.invokeSuspend(Server.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        ...
```

**Comment by angryziber** [comment]
HttpExchange.pathParams will now be initalized even in case of 404 requests
